[package]
name = "rust-ecs-test"
version = "0.1.0"
edition = "2018"
authors = ["Chance <shafferchance@gmail.com>"]

[dependencies]
winit = "0.25.0"
ash = "0.33.0+1.2.186"
#cocoa = "0.24.0"
#metal = "0.23.0"
#objc = "0.2.7"
winapi = "0.3.9"
